### ISSUE TITLE
Error when trying to parse a document

### ISSUE THREAD

**Issue by Maijin** [fhightower/ioc-finder#89]
Hi @fhightower,

I was trying to parse the following paste using 

iocs = find_iocs(text)

but I got the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/maijin/Projects/js/a", line 398, in <module>
    iocs = find_iocs(a)
  File "/usr/local/lib/python3.8/site-packages/ioc_finder/ioc_finder.py", line 453, in find_iocs
    iocs['domains'] = executor.submit(parse_domain_names, text).result()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "a", line 398, in <module>
    iocs = find_iocs(a)
  File "/usr/local/lib/python3.8/site-packages/ioc_finder/ioc_finder.py", line 453, in find_iocs
    iocs['domains'] = executor.submit(parse_domain_names, text).result()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by Maijin** [comment]
Interestingly with the cProfile on it worked here is the report - 

https://pastebin.com/s387pNFC

**Comment by fhightower** [comment]
Oh, that is strange. Thanks for reporting! I'll do some investigation.

**Comment by Maijin** [comment]
Thanks!

**Comment by Maijin** [comment]
Right now this problem is the biggest blocker for me to use this in scripts, seems to be present everytime I try to parse HTML with ioc-finder :(

**Comment by fhightower** [comment]
Ok, gotcha. I'll take a look over the next few days and see what I can figure out.

**Comment by Maijin** [comment]
Oh I thought I had it pasted that's my fault e.g pastebin.com/ubfMSn89

**Comment by fhightower** [comment]
No problem. Thanks!

Are you trying to use ioc-finder on a windows machine? I ask because I _think_ I know what the problem is and it is most likely to occur on windows machines.

After doing some research on this ([here](https://stackoverflow.com/questions/37103243/multiprocessing-pool-in-jupyter-notebook-works-on-linux-but-not-windows/41294640#41294640), [here](https://stackoverflow.com/questions/15900366/all-example-concurrent-futures-code-is-failing-with-brokenprocesspool/45302590#45302590), and [here](https://stackoverflow.com/questions/59124525/python-concurrent-futures-processpoolexecutor-fail-to-work/59320867#59320867)), I think the answer is that I do not have a block like:

```
if __name__ == '__main__':
    ...
```

in my code. I'll add a `if __name__ == '__main__'` block, but you'll have to let me know if that fixes the problem because I don't use windows machine and can't replicate this issue.

**Comment by fhightower** [comment]
I released a new version of this package (`4.0.3`) to pypi. When you get a chance, try the new version and let me know if that solves the problem. Thanks!

(This issue was addressed in commit 594b0f39971e0f3b80a92c133e6265d1f7f8088b)

**Comment by Maijin** [comment]
Still reproducible on https://pastebin.com/hL0dYK2q, I'm on Mac OS 10.15.6

**Comment by fhightower** [comment]
Ok, gotcha. In what environment are you running this package (e.g. python, ipython, or jupyter, etc.)?

I'll likely just remove multiprocessing from this app. I'm using concurrent.futures, but I've been reading that using concurrent.futures can causes errors for a number of reasons (including when code using concurrent.futures is run in an interactive interpreter).

**Comment by Maijin** [comment]
I'm using Python 3.8.5 and calling the script python3 script.py, no specifics 😃

**Comment by fhightower** [comment]
Haha, well... not sure what is going on then 😆 . Sorry about the hassle. I've released a new version (`5.0.0`) where I've removed concurrent.futures so the package will not (at least _should_ not) produce this error any more.
